### ISSUE TITLE
Is it not maintained? The site cannot be opened.

### ISSUE THREAD

**Issue by VineFiner** [FeatherCMS/feather#62]

**Comment by rdela** [comment]
https://twitter.com/tiborbodecs/status/1465240892810354692

> I decided to give Cyber Monday a shot. 🤖
>
> I'm working on #SwiftLang async / await support for both for the CMS and my book. Free update will be available as soon as I make everything work. ✅
>
> My #codevapor book is now available for $24 through this link:
https://theswiftdev.gumroad.com/l/practical-server-side-swift/6a035wm

**Comment by tib** [comment]
Yep, sorry about the silence, I was having a hard time, but I'm trying to do my best to update everything as soon as possible. :)
